cms/urls.py
from django.urls import path

#from cms import views
from . import views

app_name = 'cms'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index_page'),
    path('book/', views.book_list, name='book_list'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('book/rent/<int:book_id>/', views.book_rent, name='book_rent'),
    path('book/return/<int:book_id>/', views.book_return, name='book_return'),
]

mybook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cms.urls')),
]

cms/models.py
from django.db import models


class Book(models.Model):
    book_num = models.IntegerField('蔵書番号', unique=True)
    name = models.CharField('書籍名', max_length=255)
    publisher = models.CharField('出版社', max_length=255, blank=True)
    isavailable = models.BooleanField('貸出可否', default=True)
    renter = models.CharField('借りている人', blank=True, max_length=64)

    def __str__(self):
        return self.name

cms/forms.py
from django.forms import ModelForm

from .models import Book
from django.contrib.auth.forms import AuthenticationForm #Djangoのログオン用のモジュールをインポーと

class BookEditForm(ModelForm):
    class Meta:
        model = Book
        fields = ('book_num', 'name', 'publisher',)

class BookRentForm(ModelForm):
    class Meta:
        model = Book
        fields = ()
 #       labels = {'renter': 'なまえ'}

class LoginForm(AuthenticationForm):
    #ログインフォーム，元のAuthenticationFormクラスではusernameとパスワードがセットで格納されている
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

cms/views.py
from re import A
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic.list import ListView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from django.core.paginator import Paginator
from django.views import generic
#from cms.models import Book
#from cms.forms import BookEditForm, BookRentForm
from .forms import LoginForm, BookEditForm, BookRentForm
from .models import Book



# Create your views here.
def top(request):
    return render(request, 'cms/base.html')

class IndexView(generic.TemplateView):
    template_name = "cms/index.html"

def book_list(request):
    books = Book.objects.all().order_by('book_num')
    if "action" in request.GET:
        action = request.GET.get("action")
        if "book_num_asc" in action:
            books = books.order_by("book_num")
        elif "book_name" in action:
            books = books.order_by("name")
        elif "publisher" in action:
            books = books.order_by("publisher")
        elif "available" in action:
            books = books.order_by("isavailable")

        if "des" in action:
            books = books.reverse()
    
    paginator = Paginator(books, 10)
    if "page" in request.GET:
        books = paginator.get_page(request.GET["page"])
    else:
        books = paginator.get_page(1)

    return render(request,'cms/book_list.html',{'books': books})


def book_rent(request, book_id):
    if book_id:
        book = get_object_or_404(Book, pk=book_id)
    else:
        book = Book()

    if request.method == 'POST':
        user = str(request.user)
        form = BookRentForm(request.POST, instance=book)
        if form.is_valid():
            book.renter = user
            book = form.save(commit=False)
            book.isavailable = False
            book.save()
            return redirect('cms:book_list')
    else:
        form = BookRentForm(instance=book)

    return render(request, 'cms/book_rent.html', dict(form=form, book_id=book_id, book=book))


def book_return(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.isavailable = True
    book.renter = ""
    book.save()
    return redirect('cms:book_list')



class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'cms/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'cms/login.html'
    
#LoginRequiredMixin, 

cms/templates/cms/base.html
{% load static %}
<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'cms/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'cms/css/one-page-wonder.min.css' %}" rel="stylesheet">
    
    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'cms/css/mystyle.css' %}">
    {% include 'cms/java_function.html' %}<!-- java関数用のhtmlファイルjava_function.htmlの内容をここで挿入 -->
    {% block head %}{% endblock %}

  </head>
  <body>

	  <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
          <div class="container">
            <a class="navbar-brand" href="{% url 'cms:index_page' %}">たんぽぽ蔵書管理システム</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
              <li class="nav-item">
              {% include 'cms/login_information.html' %}
              </li>
              </ul>
            </div>
          </div>
        </nav>

        {% block header%}{% endblock %}

        {% block content%}{% endblock %}

        <!-- Footer -->
        <footer class="py-5 bg-black">
          <div class="container">
            <p class="m-0 text-center text-white small">Copyright &copy; たんぽぽ蔵書システム 2022</p>
          </div>
          <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'cms/js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'cms/js/bootstrap.bundle.min.js' %}"></script>
  	</div>
  </body>

</html>

cms/templates/cms/book_edit.html
{% extends "cms/base.html" %}
{% load bootstrap4 %}

{% block title %}書籍の編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">書籍の編集</h4>
    {% if book_id %}
    <form action="{% url 'cms:book_mod' book_id=book_id %}" method="post">
    {% else %}
    <form action="{% url 'cms:book_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:book_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/book_list.html
{% extends "cms/base.html" %}
{% load param_change %}

{% block title %}書籍の一覧{% endblock title %}



{% block content %}

  {% if user.is_authenticated %}<!-- ログインしてた場合の処理 -->

  {% else %}<!-- ログインしてない場合の処理(ログインボタンを表示)，そもそもログインしてない状態で開いたらログイン画面に飛ばす -->
    <script>
      login_display();
    </script>
  {% endif %}


<div class="container-fluid">
  <div class="row">
    <div class="mt-5"></div>
    <h4 class="mt-4 border-bottom">書籍の一覧</h4>

    <!-- 絞り込みを作ろうとして途中。 -->
    <!-- <div class="dropdown">
      <button class="btn btn-info dropdown-toggle mb-2" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        絞り込み
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
        <button class="dropdown-item" type="button" >貸出可</button>
      </div>
    </div> -->

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <form class = "mt-2 ml-2 mb-2" action="" method="GET">
          <th scope="col">蔵書番号
              <button type="submit" class="btn- " name="action" value="book_num_asc">△</button>
              <button type="submit" class="btn- " name="action" value="book_num_des">▽</button>
          </th>
          <th scope="col">書籍名
            <button type="submit" class="btn- " name="action" value="book_name_asc">△</button>
            <button type="submit" class="btn- " name="action" value="book_name_des">▽</button>
          </th>
          <th scope="col">出版社
            <button type="submit" class="btn- " name="action" value="publisher_asc">△</button>
            <button type="submit" class="btn- " name="action" value="publisher_des">▽</button>
          </th>
          <th scope="col">貸出可否</th>
          <th scope="col">借りている人</th>
          <th scope="col">操作</th>
        </form>
        </tr>
      </thead>

      <tbody>
        {% for book in books %}
        <tr>
          <th scope="row">{{ book.book_num }}</th>
          <td>{{ book.name }}</td>
          <td>{{ book.publisher }}</td>
            {% if book.isavailable%}
              <td>可</td>
            {% else %}
              <td>不可</td>
            {% endif %}
          <td>{{ book.renter }}</td>
          <td>

            {%if book.isavailable%}
              <a href="{% url 'cms:book_rent' book_id=book.id %}" class="btn btn-outline-primary btn-sm">かりる</a>
            {% else %}
              {% if book.renter%}
              {% if book.renter == user.get_username %}
                <a href="{% url 'cms:book_return' book_id=book.id %}" class="btn btn-outline-primary btn-sm">かえす</a>
              {% endif %}
              {% endif %}
            {% endif %}

          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <ul class="pagination justify-content-center">
      {% if books.has_previous %}
        <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' '1' %}"><<</a></li>
        <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' books.previous_page_number %}">{{books.previous_page_number}}</a></li>
      {% endif %}
      
        <li class="page-item"><a class="page-link">{{ books.number }}</a></li>

      {% if books.has_next %}
        <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' books.next_page_number %}">{{books.next_page_number}}</a></li>
        <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' books.paginator.num_pages %}">>></a></li>
      {% endif %}
  </ul>
  </div>
</div>

{% endblock content %}

cms/templates/cms/book_rent.html
{% extends "cms/base.html" %}
{% load bootstrap4 %}

{% block title %}かりる{% endblock title %}

{% block content %}


  {% if user.is_authenticated %}<!-- ログインしてた場合の処理 -->

  {% else %}<!-- ログインしてない場合の処理(ログインボタンを表示)，そもそもログインしてない状態で開いたらログイン画面に飛ばす -->
    <script>
      login_display();
    </script>
  {% endif %}


<div class="container-fluid">
  <div class="row">
    <div class="mt-5"></div>
    <h4 class="mt-4 mb-5 border-bottom">かりる</h4>
    {% if book_id %}
    <form action="{% url 'cms:book_rent' book_id=book_id %}" method="post">
    {# {% else %} TODO:本がないときのエラー処理をつくる #}
    
    {% endif %}
    <h5>かりる本</h5>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">蔵書番号</th>
          <th scope="col">書籍名</th>
          <th scope="col">出版社</th>
        </tr>
      </thead>
      <tbody>
        <th scope="row">{{ book.book_num }}</th>
        <td>{{ book.name }}</td>
        <td>{{ book.publisher }}</td>
      </tbody>
    </table>
      {% csrf_token %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:book_list' %}" class="btn btn-secondary btn-sm btn_sec">戻る</a>
  </div>
</div>
{% endblock content %}

cms/templates/cms/formpage.html
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Contact Form</title>
  </head>

  <body>
    <h1>コンタクトフォーム</h1>
    <p>{{ Message }}</p>

    <!-- フォームを定義 -->
    <form action="{% url 'formpage' %}" method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="送信">
    </form>

  </body>
</html>

cms/templates/cms/index.html
{% extends "cms/base.html" %}
{% load bootstrap4 %}
{% load static %}
{% block title %}
トップページ
{% endblock %}

{% block header%}
<header class="masthead text-center text-white">
  <div class="masthead content">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-4 order-lg-2">
          <div class="p-0">
            <img src="{% static 'cms/img/tanpopo2.png' %}" alt="">
          </div>
        </div>
        <div class="col-lg-4 order-lg-2">
          <div class="p-0">
            <h1 class="masthead-heading mb-0 col-lg-0 ">たんぽぽ蔵書</h1>
            <h2 class="masthead-subheading mb-0 col-lg-0">Welcome</h2>
            {% if not user.is_authenticated %}
            <a href="login/" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
            {% else %}
            <a href="book/" class="btn btn-primary btn-xl rounded-pill mt-5">蔵書リストへ</a>
            {% endif %}
          </div>
        </div>
        <div class="col-lg-4 order-lg-2">
          <div class="p-0">
            <img class="img-fluid rounded-circle" src="{% static 'cms/img/tanpopo2.png' %}" alt="">
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block content %}
<!-- <section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-10 order-lg-2">
        <div class="p-0">
          <h2 class="display-6">本の一覧、誰が借りたか分かるのはあなただけでしょうか</h2>
          <p>みなさんこんにちは</p>
        </div>
      </div>
      <div class="col-lg-2 order-lg-2">
        <div class="p-0">
          <h2 class="display-6">本の一覧、誰が借りたか</h2>
          <p>みなさんこんにちは</p>
        </div>
      </div>
    </div>
  </div>
</section> -->
{% endblock %}

cms/templates/cms/java_function.html
<!-- java関数定義用のhtml -->
<!-- ここで定義すればbase.htmlでインポートしてるのでそれ周りでは基本使えるよ -->

    <!--トップページに強制的に飛ばすための関数，とりあえずトップページに飛ぶようにしてるけど引数とって任意のところにするのもあり -->
    <!-- httpの時しか使えない，両方使えるようにする方法がわからなかった．解決策あればよろしく -->
    <script>
      function login_display(){
        host = location.host
        topurl = 'http://' + host
        location.replace(topurl);
      }
    </script>

cms/templates/cms/login.html
{% extends "cms/base.html" %}
<!DOCTYPE html>
{% block title %}ログインページ{% endblock title %}

{% load static %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="mt-5"></div>
    <div class="mt-5"></div>
    <form action="" method="POST">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group has-feedback form_long">
          {{ field }}
        </div>
      {% endfor %}
      <div class="row">

        {% for error in form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            <p>{{ error }}</p>
          </div>
        {% endfor %}
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">ログイン</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:index_page' %}" class="btn btn-secondary btn-sm btn_sec ">戻る</a>
  </div>
</div>
{% endblock content %}

cms/templates/cms/login_information.html
  <!-- ここからログインに関する部分 -->
  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
        <!-- ログインしてるか判断させるif文 -->
        {% if user.is_authenticated %}<!-- ログインしてた場合の処理 -->
          <li>
              <!--ユーザー名をとってきて表示させる user.get_usernameでユーザー名はとってこれる-->
              <a class="nav-link">ユーザ名：{{ user.get_username }}</a>
          </li>
          <li>
            <!-- ログアウトボタンを押したらログアウトの関数を実行するよう設定 -->
            <a class="nav-link" href="{% url 'cms:logout' %}">
            <!-- ログアウトボタン本体の作成 -->
            <i class="fa fa-fw fa-sign-out"></i>ログアウト</a>
          </li>
        {% else %}<!-- ログインしてない場合の処理(ログインボタンを表示)，そもそもログインしてない状態で開いたらログイン画面に飛ばす -->
          <!-- <script>
            login_display();
          </script> -->
        <!--
          <li>
            ログインボタンを押したらログインの関数を実行するよう設定
            <a class="nav-link" href="{% url 'cms:login' %}">
            ログインボタン本体の作成
            <i class="fa fa-fw fa-sign-in"></i>ログイン</a>
          </li>
        -->
        {% endif %}
    </ul>
  </div>
  <!-- ここまでログインに関する部分 -->